version: '2'
services:
   centerservice:
       container_name: orderservice-1
       build:
          context: .
          dockerfile: Dockerfile
       restart: always
       ports:
       - "8001:8001"
       volumes:
       - ../target/OrderService.jar:/root/target/OrderService.jar
       networks:
       - java110-net
       mem_limit: 1024m
       extra_hosts:
       - "dev.java110.com:192.168.8.108"
       - "dev.db.java110.com:192.168.8.108"
       - "dev.zk.java110.com:192.168.8.108"
       - "dev.kafka.java110.com:192.168.8.108"
       - "dev.redis.java110.com:192.168.8.108"
       - "api.java110.com:192.168.8.108"
networks:
  java110-net:
    external: true